### ISSUE TITLE
ServerTest doesn't always succeed

### ISSUE THREAD

**Issue by petterdaae** [inf112-v19/Bender#47]
Seperate these tests from the other tests such that they don't stop the project from building

**Comment by petterdaae** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "WebSocketSelector-21" java.lang.NullPointerException
	at inf112.skeleton.app.server.ServerMain.onError(ServerMain.java:92)
	at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:618)
	at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:514)
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
	at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "WebSocketConnectReadThread-22" java.lang.NullPointerException
	at inf112.skeleton.app.server.RemoteServerHandler$WSC.onError(RemoteServerHandler.java:156)
	at org.java_websocket.client.WebSocketClient.onWebsocketError(WebSocketClient.java:536)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:412)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by PabloDons** [comment]
This is an error with port binding when the same port is already bound by another program. A quick fix is forcibly unbinding the port or waiting a few seconds for your OS to do it. This often happens when the program is interrupted before the server can gracefully exit. 

I'll think about a fix, but it doesn't really happen under normal circumstances.
